# Generated by Django 6.1.1 on 2026-10-09 10:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_profile_activity_alter_profile_goal'),
        ('products', '0002_remove_product_unique_product_name_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('meal_type', models.CharField(choices=[('breakfast', 'завтрак'), ('lunch', 'обед'), ('dinner', 'ужин'), ('snack', 'перекус')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='accounts.profile')),
            ],
            options={
                'ordering': ['date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_grams', models.FloatField(help_text='вес порции в граммах', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('calories', models.FloatField(default=0, editable=False)),
                ('proteins', models.FloatField(default=0, editable=False)),
                ('fats', models.FloatField(default=0, editable=False)),
                ('carbs', models.FloatField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diary.meal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_items', to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('profile', 'date', 'meal_type'), name='unique_meal_per_profile_per_day'),
        ),
    ]
