# Generated by Django 6.1.1 on 2026-10-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('height', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Мужчина'), ('Female', 'Женщина')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
