# Generated by Django 6.1.1 on 2026-10-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_activity_alter_profile_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activity',
            field=models.CharField(blank=True, choices=[('sedentary', 'Минимальная (сидячая)'), ('light', 'Легкая (5000+ шагов в день)'), ('moderate', 'Средняя (2-3 тренировки в неделю + 7000+ шагов в день)'), ('active', 'Высокая (3+ тренировки в неделю + 10000+ шагов в день)'), ('very_active', 'Очень высокая (физическая работа прим.Работа на стройке)')], default='sedentary', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(blank=True, choices=[('lose', 'Похудение'), ('maintain', 'Поддержание'), ('gain', 'Набор веса')], default='maintain', max_length=10, null=True),
        ),
    ]
