# Generated by Django 6.1.1 on 2026-10-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_name_brand',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'brand'), name='unique_product_name_brand', nulls_distinct=False),
        ),
    ]
